### ISSUE TITLE
Using Mac

### ISSUE THREAD

**Issue by jinc132** [null-uw/Beacon#18] opened 2019-06-11 21:42 UTC
I followed the instructions to install the app for mac and iOS and it install. However, I could not get it running.

**Comment by matthewkli97** [comment] 2019-06-12 05:28
In our deployment documentation, we do mention that we prioritized the deployment of our application to Android devices but do provide the instructions for iOS. The development of our application was primarily performed on Mac devices following the same instructions outlined in our deployment doc. 

After investigating, our team was unable to reproduce the issue based on the information and context that was provided by the author. Our deployment documentation for iOS are links to official Flutter deployment documentation which, based on Google's enterprise status and reputation, we do not believe is incorrect and closing this issue as a **non-issue**

**Closed as completed by matthewkli97** 2019-06-12 05:28 UTC
